### ISSUE TITLE
Incorrect type $Mail.ProfileNumber

### ISSUE THREAD

**Issue by iga566** [EvotecIT/PSOutlookProfile#1]
If ProfileNumber 10 or greater, error :

`[int] $PrimaryProfile = $Mail.ProfileNumber
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastFromStringToInteger`

**Comment by PrzemyslawKlys** [comment]
Thanks for reporting. I'll take a look
