### ISSUE TITLE
Problem with Outlook 2013

### ISSUE THREAD

**Issue by cortesmario** [EvotecIT/PSOutlookProfile#3]
Hi,

I am trying the modules to solve the problem “The primary account cannot be removed unless it is the only account in the profile. You must remove all other Exchange accounts before removing the primary account.”

https://evotec.xyz/outlook-the-primary-account-cannot-be-removed-unless-it-is-the-only-account-in-the-profile/

Our configuration are:
•	Windows 7
•	Outlook 2013

I have the problem that the Account Name are hex code and not legible characters like Outlook 2016.
For example, AccountName: {76, 0, 105, 0...}

![Outlook_2013_Registry](https://user-images.githubusercontent.com/68321555/87517523-3b85eb80-c67f-11ea-87f2-3c65fc8a2127.png)

Do you known any solution to this?

Thanks and best regards,
Mario

**Comment by PrzemyslawKlys** [comment]
Hi,

You could try using private function:

```powershell
function Convert-BinaryToString {
    param(
        [alias('Bin')]
        [Parameter(Position = 0, Mandatory = $false, ValueFromPipeline = $true)]
        [Byte[]]$Binary
    )
    if ($null -ne $Binary) {
        return [System.Text.Encoding]::Unicode.GetString($Binary)
    }
}
```

To see if it will help with account name translation. If it does... we would need to somehow incorporate it into the code. I've not used Outlook 2013 for a while.

PS. I got your email, but GitHub is better for those queries.

**Comment by cortesmario** [comment]
> ```powershell
> Convert-BinaryToString
> ```

Hi,

I add the line "$TextAccountName = Convert-BinaryToString $AccountName" and now if I show the TextAccountName variable value, this is a String text.

But when I execute the command "Start-OutlookProfile -NoBackup -WhatIf -RemoveAccount 'nameofaccount'.
Show that remove key form registry, but all accounts are in the profile.

Have I to change anything more at the script? Are the command correct?

Thanks and best regards,
Mario

**Comment by cortesmario** [comment]
Hi,

I execute the command without the "WhatIf" parameter and the account disappear from the profile, but If I open the Outlook the deleted mailbox still appears.

I logout and doesn´t solve. I restart the computer and doesn´t solve.

**Comment by PrzemyslawKlys** [comment]
Just to clarify, once you added that $TextAccountName it confirms what you expected? 

I don't think it's that easy as changing it in one place. You would need to change it in all other places so it know what it is deleting. 

I have no Office 2013 or Windows 7 to try and help you out, but Removeaccount that you use in Start-OutlookProfile most likely needs to be compared against converted $TextAccountName in places changing how things are done. This requires debugging and step by step scenario seeing what happens. 

Reboot is not necessary to see changes.

**Comment by cortesmario** [comment]
Hi,

Just to clarify, once you added that $TextAccountName it confirms what you expected?
Yes its works that I expected. The delete seems to work fine, because the keys are deleted, but the deleted mailbox still appears but doesn´t show at profile config. Seems that we need to delete more keys.

**Comment by PrzemyslawKlys** [comment]
Deletion is one thing, but you need to then change primary account which may be different to what you expect it to.

**Comment by cortesmario** [comment]
Hi,

The script are working now. Only have one problem and are that the "Data File" doesn´t appear as Principal" with the "Black OK". The Outlook show an error but If I check the file as Principal all works fine.

Do you know how I can make this step with the registry?
Thanks,

**Comment by PrzemyslawKlys** [comment]
I don't think I've touched the subject of Data File in my original work. If you could share your findings to this project after you're done that would be great. I'm sure other people would love this to support 2013.

**Comment by cortesmario** [comment]
I don´t think how to solve this last issue. But I better than anything.

How Can I send you the files that change to Outlook 2013? And almost the key are the "delete account text" that I expecify.

**Comment by PrzemyslawKlys** [comment]
You can attach it here - it's enough I guess.

**Comment by cortesmario** [comment]
Finally,
I review the scripts, because I think that are working but almost leave some registry keys without delete. The problem are that are key in the 001f6641 value Outlook 2016 and 001f662b Outlook 2013. I need to make the Find-OutlookKeys.ps1 to look the two keys. When I have the files I upload.

**Comment by cortesmario** [comment]
Hi,

With these files are working now. Only have two issue but I don´t know how solve:
- In a configuration with one IMAP Mailbox and one Exchange Mailbox. I want to remove the Exchange account. Seems to work fine because the information of Exchange Mailbox doesn´t show in Outlook, but if you show the profile information the Echange Mailbox are show. I delete form here and everything OK.
- In a configuration with two Exchange Mailboxes. I want to remove one of the Exchange account. Seems to work fine because the information of Exchange Mailbox doesn´t show in Outlook, but if I mapped a pst the file account default are the pst and not the file and if I doesn´t map the pst I have to enter in profile configuration to check the correct default file.

Do you know how assign these default file? 
I implemented the solution with this little errors.
[PSOutlookProfile.zip](https://github.com/EvotecIT/PSOutlookProfile/files/4958191/PSOutlookProfile.zip)

**Comment by PrzemyslawKlys** [comment]
Unfortunetly I don't. I have managed to do what I showed on blog post and what you see here on GitHub. I was out of time to dig deeper.
